### ISSUE TITLE
emotivedf.cpp segfaults during reading process

### ISSUE THREAD

**Issue by ishiikurisu** [ishiikurisu/EEG#2]
Trying to read a *.edf file using emotivedf.cpp segfaults. Compiling instructions:
``` makefile
g++ emotivedf.cpp -o emo.exe -lm -O2 - pipe -ansi -Wall
```
backtrace in gdb:
``` makefile
#0  0x6fc5e26c in libstdc++-6!_ZNKSs7_M_dataEv ()
   from C:\MinGW\bin\libstdc++-6.dll
#1  0x6fc5e1a3 in libstdc++-6!_ZNKSs6_M_repEv ()
   from C:\MinGW\bin\libstdc++-6.dll
#2  0x6fc5df4b in libstdc++-6!_ZNKSs4sizeEv ()
   from C:\MinGW\bin\libstdc++-6.dll
#3  0x6fc5e2c3 in libstdc++-6!_ZNKSs7compareEPKc ()
   from C:\MinGW\bin\libstdc++-6.dll
#4  0x00404259 in _fu61___ZNSs4_Rep20_S_empty_rep_storageE ()
#5  0x004100bb in _Jv_RegisterClasses ()
#6  0x0040e09e in _fu117___ZSt3cin ()
#7  0x77c3fce0 in msvcrt!_iob () from C:\WINDOWS\system32\msvcrt.dll
#8  0x00410177 in _Jv_RegisterClasses ()
#9  0x00401250 in __mingw_CRTStartup ()
#10 0x004012b5 in mainCRTStartup ()
```

**Comment by ishiikurisu** [comment]
This issue has now been solved, but at the cost of not making a correct reading of data, since it doesn't read the number of sampeles in correct place.

**Comment by ishiikurisu** [comment]
It now reads correctly the number of samples.
